name: CICD
on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      # what is the difference between npm ci and npm install
      - run: npm run format:check 
      - run: npm test -- --coverage
        env:
          CI: true
      
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build

      - name: Deploy to staging environment
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain truculent-profit.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ sercrets.SURGE_TOKEN }}

