name: CICD
on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      # what is the difference between npm ci and npm install
      - run: npm run format
      - run: npm run format:check  
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3 
        with:
          name: code-coverage
          path: coverage
      - name: Build Project
        if: github.event_name == 'push'
        run: |
          npm run build
      - name: Upload Build Coverage
        uses: actions/upload-artifact@v3 
        with:
          name: build
          path: build
      - name: Deploy to staging environment
        if: github.event_name == 'push'

        # https://www.freecodecamp.org/news/error-error-0308010c-digital-envelope-routines-unsupported-node-error-solved/
        run: |
          # npx uninstall react-scripts
          # npx install react-scripts
          npx surge --project ./build --domain truculent-profit.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
